[features]
seeds = false
[programs.devnet]
pandora = "ERCw53LxmDDUZsjay7nRyPJJcHkEWEvxxLZ8bmeYWJDf"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/ademola/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/pandora.ts"
